import type { Metadata } from "next";
import { Playwrite_CO, Manrope } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/components/providers/provider.reactQuery";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const playwrite = Playwrite_CO({
  variable: "--font-playwrite",
});

const manrope = Manrope({
  variable: "--font-manrope",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playwrite.variable} ${manrope.variable} font-manrope`}
      >
        <ReactQueryProvider>
          {children}
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
