import type { Metadata } from "next";
import { Playwrite_CO, Manrope } from "next/font/google";
import "./globals.css";

const playwrite = Playwrite_CO({
  variable: "--font-playwrite",
});

const manrope = Manrope({
  variable: "--font-manrope",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playwrite.variable} ${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
}
